### ISSUE TITLE
class 'GFRemove' does not have a method 'members_get_capabilities'

### ISSUE THREAD

**Issue by tmuka** [bhays/gravity-forms-remove-entries#1]
Hi, many thanks for the useful plugin!

I'm trying to clean up my site error logs, and it seems it's this plugin that is causing a conflict with the "Members" add-on support built in to GravityForms.

`[Fri Apr 29 11:22:43.185851 2016] [fcgid:warn] [pid 9196] [client :60139] mod_fcgid: stderr: PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, class 'GFRemove' does not have a method 'members_get_capabilities' in /var/www/vhosts/example.com/httpdocs/wp-includes/plugin.php on line 235, referer: http://www.example.com/wp-admin/plugins.php`

I found this reference to the same/simliar issue
https://wordpress.org/support/topic/after-making-custom-roles-you-can-no-longer-edit-them?replies=2

My WP and plugins are updated to the latest versions.  Disabling this plugin fixes the warnings.  

It's possible it's a GravityForms add-on implimentation bug too, so i have logged a support request there too.

**Comment by bhays** [comment]
Thanks for the heads up, please check 7ea669a5b35d9ce2edcd3088e66a943855d1568d and that should fix the warnings. I'll push a copy to the WordPress repo shortly as well.

**Comment by tmuka** [comment]
Excellent, that cleaned up the messages, thanks!

I did notice the changelog in the git readme.md says version 0.3.2 twice instead of 0.3.3. readme.txt is correct. hope this helps!
