### ISSUE TITLE
Gravity Forms suppress/conditional send to Highrise?

### ISSUE THREAD

**Issue by TPH31** [bhays/gravity-forms-remove-entries#2]
Hi.

Is it possible to disable/prevent the HR update based on the value of a form field?

Perhaps add a rule/condition section after the field mappings?

If it's not worth updating the plugin, I'd even add the code/function myself, if i could get hint here to do it.

thanks

-Tom

**Comment by bhays** [comment]
Hi Tom,

I think you've posted this on the wrong repo as you meant https://github.com/bhays/gravity-forms-highrise-crm

It is possible to do and I've done it with other similar plugins, you can see https://github.com/bhays/gravity-forms-convio/blob/master/gravity-forms-convio.php for an example.

Unfortunately my schedule right now doesn't have time to make these updates, but you're free to try and submit a pull request.

Thanks,

Ben
